### PR TITLE
[GreenDonut] Removed libraries available as part of framework from the reference list.

### LINKED ISSUE #6868: Remove dependencies from Green Donut when provided by framework
### Product

Green Donut

### Is your feature request related to a problem?

I want to reduce the package size & amount of dependencies to reduce surface area for CVE'S.

### The solution you'd like

I would like that any dependency that can be provided by the framework ie System.Text.Json the framework is leveraged to reduce dependencies.

### PR DESCRIPTION
**Pull request by thompson-tomo**
### Summary of the changes

- Removed conditions for net standard 2.1 as not a TFM
- Removed System.Threading.Tasks.Extensions & System.Diagnostics.DiagnosticSource from dependendencies when TFM is not net standard 2.0 due to being provided by Framework

Closes #6868

### CODE REVIEW

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
Hey @thompson-tomo,

thanks for your work on this. Do you want to move on to Hot Chocolate and do the same there?

**Comment by thompson-tomo** [comment]
@michaelstaib Sure thing, can u re-open the existing issue or do you want me to create a new one or simply link to the closed one?

**Comment by michaelstaib** [comment]
Hey @thompson-tomo,

as these are maintenance tasks a PR is enough.

**Comment by thompson-tomo** [comment]
Pr all submitted for Hot Chocolate.

**Pull request merged**
