### PR TITLE
Support F# Records and Options

### PR DESCRIPTION
**Pull request by AlexeyRaga**
[Taking over PR #5595]

### Adds support for F# options

- Exposing an OptionTypeConverter for use
- Correctly "unnesting" options in the TypeInfo class

Adds an F# integration test to HotChocolate.Core

### CODE REVIEW

**Comment by AlexeyRaga** [comment]
@michaelstaib @PascalSenn I am taking over the #5595 because unfortunately @nordfjord is not able to work on it anymore.
The PR (#5595) can now be closed.
This PR is rebased after current `main` and is fixed.

Could you please review and let me know if it can be merged or if you want something to change?

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
I have merged this into the main branch aka version 14.

**Comment by michaelstaib** [comment]
I will include it into the next preview build for 14 ... end of the week I think.

**Comment by pblasucci** [comment]
Thanks @AlexeyRaga and @nordfjord !!! This is really exciting stuff.

**Pull request merged**
