### PR TITLE
Change mistaken "filtering" wording

### PR DESCRIPTION
**Pull request by Kayyow**
- Replace "filtering" with "projections" wording on the projections page

### CODE REVIEW

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
@Kayyow can you sign the CLA please.

**Review by michaelstaib — CHANGES_REQUESTED** [review]
We cannot merge without CLA

**Comment by Kayyow** [comment]
Done @michaelstaib, sorry for de delay !

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
Thanks for your help on the project!

**Pull request merged**
