### PR TITLE
Redundant IHasScope removed

### PR DESCRIPTION
**Pull request by nirzaf**
- Base interface 'IHasScope' is redundant because HotChocolate.Data.Filters.FilterFieldDefinition implements 'IFilterFieldDefinition' which contains IHasScope interface in it already

### CODE REVIEW

**Comment by michaelstaib** [comment]
Thank you for contributing.

@MFM_Fazrin also needs to sign the CLA for this to procede.

**Comment by michaelstaib** [comment]
@PascalSenn can you verify the change?

**Comment by nirzaf** [comment]
> Thank you for contributing.
> 
> @MFM_Fazrin also needs to sign the CLA for this to procede.

I already Signed, I don't how the other name "MFM_Fazrin" appear there, I have only one account with the username "nirzaf", and I could not Sign on behalf of "MFM_Fazrin" it is a request to add an email linked to this account, but I don't use any other account

**Review by PascalSenn — APPROVED** [review]

**Comment by michaelstaib** [comment]
Its the email that you have in your local git config: mmfazrin@phcc.gov.qa

**Comment by michaelstaib** [comment]
I will squash the commit and then this email will be gone.

**Pull request merged**
