### PR TITLE
Ignore computed read-only properties when inferring InputObjectType fields

### LINKED ISSUE #5673: Ignore read-only properties in a binding type of InputObjectType from inferred fields
### Product

Hot Chocolate

### Is your feature request related to a problem?

It would be great if I can reuse a binding type for both `ObjectType` and `InputObjectType`, without configuring.

Given application fails to startup:

```cs
using HotChocolate.Execution;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddGraphQLServer()
    .AddQueryType(type => type.Field("foo").Resolve(() => "bar"))
    .AddMutationType<Mutation>()
    .InitializeOnStartup()
    ;

var app = builder.Build();

var executor = await app.Services.GetRequestExecutorAsync();
Console.WriteLine(executor.Schema);

public class Mutation {
    public Metadata PutMetadata(Metadata input) => input;
}

public class Metadata {
    public Metadata(int id) {
        Id = id;
    }

    public int Id { get; }
    public int Hash => Id;
}
```

with an exception that it cannot set value to `Metadata.Hash`:
```
Unhandled exception. System.InvalidOperationException: No compatible constructor found for input type type `Metadata`.
Either you have to provide a public constructor with settable properties or a public constructor that allows to pass in values for read-only properties. There was no way to set the following properties: .
   at HotChocolate.Utilities.Serialization.InputObjectConstructorResolver.GetCompatibleConstructor[T](Type type, FieldCollection`1 fields, IReadOnlyDictionary`2 fieldMap)
   at HotChocolate.Utilities.Serialization.InputObjectCompiler.CompileFactory(InputObjectType inputType, ConstructorInfo constructor)
   at HotChocolate.Types.InputObjectType.OnCompleteCreateInstance(ITypeCompletionContext context, InputObjectTypeDefinition definition)
   at HotChocolate.Types.InputObjectType.OnCompleteType(ITypeCompletionContext context, InputObjectTypeDefinition definition)
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
   at HotChocolate.Configuration.TypeInitializer.CompleteType(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>b__29_0(RegisteredType type)
   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(String schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(String schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /Users/sunghwan2789/Desktop/csharp/Program.cs:line 13
   at Program.<Main>(String[] args)
```

I think it is normal when fields are bound explicitly, but implicit binding could ignore some read-only properties.

### The solution you'd like

Human-generated read-only properties are ignored from inferred fields of `InputObjectType`.

For example, 
* `typeof(Metadata).GetProperty(nameof(Metadata.Id)).GetMethod.GetCustomAttribute<CompilerGeneratedAttribute>()` is not null, so it is included.
* `typeof(Metadata).GetProperty(nameof(Metadata.Hash)).GetMethod.GetCustomAttribute<CompilerGeneratedAttribute>()` is null, so it is ignored.

Expecting generated schema:

```gql
type Mutation {
  putMetadata(input: MetadataInput!): Metadata!
}

input MetadataInput {
  id: Int!
}

type Metadata {
  id: Int!
  hash: Int!
}
```

Related code, maybe?

https://github.com/ChilliCream/hotchocolate/blob/af14b1ff0e1e2dfea9deb0912b274f7dc57aacd7/src/HotChocolate/Core/src/Types/Types/Descriptors/InputObjectTypeDescriptor.cs#L100

### PR DESCRIPTION
**Pull request by atykhyy**
**Product**: HotChocolate

Adds a simple check to ignore computed read-only properties when binding an InputObjectType from inferred fields.
~The check does not analyze the getter body and cannot distinguish between real computed properties and old-style read-only properties which simply return a read-only field initialized in a consstructor, but it should cover the overwhelming majority of use cases.~

Closes #5673

### CODE REVIEW

**Comment by michaelstaib** [comment]
I have some further thoughts. Wouldn't it be better if we solved this particular problem with a source generator that creates the formatter and parser. We have started shifting some problems into this area? What are your thoughts?

**Comment by atykhyy** [comment]
1. As far as I understand, method IL is in memory anyway, and the cost of the check is trivial, just a couple of reflection calls.
2. AOP and code generation happen before the assembly loads. The check operates on the getters that will actually execute, so it should work regardless.
3. I think this is a much more serious concern. There may be quite a few such patterns users may want to handle, and someone is bound to be unhappy with any hard-coded set of patterns. I have since found that I can handle the issue that prompted this PR on my side by configuring my input object types, so I no longer think that the approach above is a good idea. I have two other suggestions instead:

* Add a `TypeContext` parameter to `ITypeInspector.GetMembers` so that custom implementations can choose to omit members specifically when HC infers fields for input object types. This would enable the author of #5673 (and me) to deal with the issue with a few lines of code as long as they control the code base and know which property patterns are in use / allowed by code style.
* Add something like `IInputObjectTypeDescriptor.Field(MemberInfo)` because right now I have to construct a LINQ expression around a property just so that `InputObjectTypeDescriptor<T>.Field` can call `ExtractMember()` on it to get the property back out.

**Comment by michaelstaib** [comment]
> AOP and code generation happen before the assembly loads. The check operates on the getters that will actually execute, so it should work regardless.

With AOP there should be no longer any IL code as I understand it ... there also os no longer a JIT. They for compatibillity allow expression compilation but they are interpreted. We have just started looking into, so I have to read up on a lot of stuff regarding AOP.

> Add a TypeContext parameter to ITypeInspector.GetMembers so that custom implementations can choose to omit ... 

That sounds like a good idea, we can do that. But since its a breaking change it will only become available with version 14.

**Comment by atykhyy** [comment]
> With AOP there should be no longer any IL code as I understand it ... there also os no longer a JIT.

Perhaps you mean AOT (ahead of time) compilation? If I remember correctly, AOP stands for aspect-oriented programming. If you mean AOT then yes IL analysis may well stop working. I don't know how much metadata is retained in AOT's output.

> That sounds like a good idea, we can do that. But since its a breaking change it will only become available with version 14.

I can live with `Configure` for now, but I can make a PR and try it out.

**Comment by atykhyy** [comment]
It should almost certainly be a separate PR, so I'll close this one.

**Pull request closed without merging**
