### PR TITLE
added condition to check for absolute path in GraphQLGenerationRoot i…

### LINKED ISSUE #5532: Strawberry Shake's generated code does not handle custom output directory properly.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Our repo is setup as follows. (We are using [NX](https://nx.dev/) for managing build orchestration/targets/dependencies/artifacts). We have a custom output directory set in our root Directory.Build.props that is set to an absolute path. (/home/krbourg/code/alloy/dist)

```
/dist/libs/shared/infrastructure/strawberry-shake-server-client/bin/*
/dist/libs/shared/infrastructure/strawberry-shake-server-client/obj/*
/libs/share/infrastructure/strawberry-shake-server-client
/Directory.Build.props
```

We are seeing the Strawberry Shake code generation output files to the following location:
`/libs/shared/infrastructure/strawberry-shake-server-client/home/krbourg/work/code/alloy/dist/libs/shared/infrastructure/strawberry-shake-server-client`
It seems to be taking our absolute path, and treating it as if it should be relative to the project directory.

### Steps to reproduce

1. Create new dotnet project within a nested folder and add strawberry shake + schema/operations. (We used StrawberryShake.Server & StrawberryShake.Tool)
2. Add a Directory.Build.props file to the root directory and specify an absolute path for the `<BaseIntermediateOutputPath>` property.
3. Build project and observe the code generated relative to the project directory.

### Relevant log output

_No response_

### Additional Context?

_No response_

### Product

Strawberry Shake

### Version

13.0.0-preview.76

### PR DESCRIPTION
**Pull request by AlexandraChibisov**
--used IsPathRooted function for the check
--this condition should check if user provided absolute path

Closes #5532

### CODE REVIEW

**Comment by michaelstaib** [comment]
can you sign the cla?

**Comment by AlexandraChibisov** [comment]
Hi,

Pretty sure I just signed it? Let me know if it didn’t go through.

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
The fix actually was correct but did address the wrong property.

**Comment by michaelstaib** [comment]
Fix is in #5770

**Pull request closed without merging**
