### PR TITLE
Add configurable access for generated clients (#6374)

### LINKED ISSUE #6374: Strawberry Shake: Configurable access for generated clients
### Product

Strawberry Shake

### Is your feature request related to a problem?

The strawberry shake client types are generated with the `public` access modifier. This is inconvenient for apps that are broken into multiple assemblies that want to hide their implementation details from each other.

### The solution you'd like

 It'd be nice if we could configure the access modifier in `graphqlrc.json`. I'd even argue that internal should be the default.

### PR DESCRIPTION
**Pull request by nih0n**
Add an option in `graphqlrc.json` to specify the access modifier of generated clients, the default access modifier is `internal`.

Closes #6374

### CODE REVIEW

**Review by michaelstaib — COMMENTED** [review]
This looks already quite good!

Can you add a source code generation test like we did here:
https://github.com/ChilliCream/graphql-platform/blob/d7b84630de9786bc0f73653970f5f6811fc181a8/src/StrawberryShake/CodeGeneration/test/CodeGeneration.CSharp.Tests/StarWarsGeneratorTests.cs#L10

You can pass in the generator settings into the assert method ... so that we have the effects of the new modifier under test?

**Comment by nih0n** [comment]
I added a new property to `AssertSettings` so you can specify the access modifier. Also made changes to the `GetAccessModifier` method, so now only `public` and `internal` are supported (as private and protected classes are doesn't make any sense)

**Comment by nih0n** [comment]
> When looking at the snapshot ... only the client seems to be internal ... models and all other types are still public.

Fixed, now interfaces, enums, and other models (inputs, results, etc) can be made internal. However the method and properties generation we're not changed, since if you set the class to internal the methods and properties wouldn't be accessible outside the assembly.

**Comment by nih0n** [comment]
> When looking at the snapshot ... only the client seems to be internal ... models and all other types are still public.

Done, however the generated methods and properties are still public, I'll mark this PR as draft till a fix that. Let me know if the current changes are enough.

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
Thank you for contributing ... your PR is merged and we have integrated the changes into this release:
https://github.com/ChilliCream/graphql-platform/releases/tag/13.5.0-preview.24

**Pull request merged**
