### PR TITLE
Add extension point to DocumentAnalyzer to change schema transformation before creating OperationModel

### PR DESCRIPTION
**Pull request by cezarypiatek**
Hi,

I would like to use Strawberryshake.CodeGeneration library to create my own tool for generating Graphql clients.
However,  I need to get an Operation model for the original schema, without any modifications so I abstracted away the part responsible for rewriting the schema before creating OperationModel. This is a small refactor that does not introduce any functional changes.

### CODE REVIEW

**Comment by michaelstaib** [comment]
@cezarypiatek why don't you join our work on strawberry shake instead of creating yet another client? We could use any help :) 

Regarding this change. We are not done yet with version 13 and want to rewrite the analyzer. At its current iteration it has some major flaws to it when using fragments that are on the same level. Also, fragments that are not used in operations have issues. So, there will be a rewrite.

**Comment by cezarypiatek** [comment]
Hi @michaelstaib, thanks for the quick response.
I would like to create a generator that creates clients based on the Query Object Pattern which is totally different from what Strawberry Shake offers atm. When I have a working version, then I will be more than happy to contribute my results to this repository. However, I'm blocked by those extra schema rewrites that I need to opt-out somehow.

**Comment by michaelstaib** [comment]
I will restart work on Strawberry Shake mid december and will abstract something for you. The current analyzer has a couple of issues that I want to rework. The contract will look different after that. Let me get that done first and then I open it for you. Sounds good?

**Comment by cezarypiatek** [comment]
Thanks. My expectation here is to have a component that accepts as input graphql files (schema  + queries) and produces as an output a "semantic" model for them, without any extra modifications.

**Comment by michaelstaib** [comment]
Exactly :)

**Pull request closed without merging**
