### PR TITLE
nitpicky debug assert fix

### PR DESCRIPTION
**Pull request by keberle**
I am working on adding a new Subscription provider for Azure Web PubSub and ran across this small bug in the Redis provider.  It seemed like an easy first pull request into your repo.

### CODE REVIEW

**Comment by michaelstaib** [comment]
Thank you for the fix... can you sign the CLA so that we can merge your fix?

**Comment by michaelstaib** [comment]
> Kyle Eberle seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

You accounts do not match

**Comment by keberle** [comment]
I switched my primary email back to my work email and went back in and signed the CLA.  Sorry about this mixup.  I forgot that I had switched it to comply with a partner's PR requirements.  I'll just leave it that way for now.

**Comment by keberle** [comment]
I cannot figure out how to get the license/cla step to show as signed.  If I click on the link, it says that it's unsigned, then refreshes and says that I've signed it so some link is clearly broken.  I am not sure what its linked to but I've changed my email back and forth between the two that were verified on the account and can't get it to acknowledge the signing on the PR.  I'll withdraw my PR.

**Pull request closed without merging**
