### PR TITLE
Add header to disable null-bubbling

### PR DESCRIPTION
**Pull request by tobias-tengler**

### CODE REVIEW

**Comment by michaelstaib** [comment]
This would create a non-spec compliant GraphQL server. We have discussed this in the working group and all agreed that it should not be a default in a GraphQL server. However we could allow it with a header, its the same idea as with the directive ... the client opts into this behaviour.

**Comment by tobias-tengler** [comment]
@michaelstaib We're in full control of all the clients and can ensure that they can handle it. So the server not being spec-compliant wouldn't be an issue for us.

Of course we could also use the current `@nullBubbling` directive, but then devs have to remember to add it and we'd like it to be the default.

Switching to the current spec proposal with the `@semanticNonNull` directive (later a type wrapper like `~!`) would also work for us. Would this be preferable?

**Comment by michaelstaib** [comment]
You can adopt the new spec directive, but having it as default is not a good idea.

**Comment by michaelstaib** [comment]
However, with a header you can move this into the network layer and no one has to think about it.

**Comment by tobias-tengler** [comment]
Okay, then I'll switch this from a schema option to a header.

**Comment by michaelstaib** [comment]
Can you post a link to the rfc?

**Comment by tobias-tengler** [comment]
I thought this was the current proposal people were getting behing: https://github.com/graphql/graphql-spec/pull/1065

**Comment by michaelstaib** [comment]
Lets see ... what I can include is a header approach at the moment. I can see that we include the draft with V14 but the new syntax `!String` seems still a bit odd :)

The header we can keep in even after the proposal is merged and is only implemented once in the client network layer.

**Comment by glen-84** [comment]
> but the new syntax !String seems still a bit odd :)

Ya, I really [dislike it](https://github.com/graphql/graphql-wg/discussions/1410#discussioncomment-7722238).

I prefer [Lee's proposal](https://github.com/graphql/graphql-wg/discussions/1410) (though I may not fully understand all of the finer details).

**Comment by tobias-tengler** [comment]
Me too. I'd love ? for nullable and unadorned for non-null (can be null for error). But I guess the new proposal is the most backwards compatible...

**Comment by michaelstaib** [comment]
@glen-84 @tobias-tengler in the spec working group we need to make sure that every graphql query that ever was created works when upgrading to a newer GraphQL spec.

While when exploring features its good to explore without compromise once you decide for an improvement it must make sure that older queries against the same type system are not breaking.

This is especially painful with introspection.

If you want to make a breaking change it must be worth the cost of the ecosystem upgrading and breaking lots of applications.

**Comment by michaelstaib** [comment]
Do not get hung up on syntax yet. I will do a prototype for V14 tonight ...

**Comment by michaelstaib** [comment]
I have started implementing the proposal today ... this will be a high impact change.

We will have a new schema option that specifies the NonNull inference. By default we will infer them as strict NonNull types to keep compatibility.

Newer servers should opt into the new behavior.

```csharp
services
    .AddGraphQLServer()
    .ModifyOptions(o => o.NonNullInference = NonNullInferenceKind.SemanticNonNull);
```

With this set all non-null C# types are now inferred as semantic non-null types. In order to explicitly make something strict non-null in this case we need a new annotation.

```csharp
[StrictNonNull]
public string Hello() => "Hello";
```

New attributes:
- `StrictNonNullAttribute`
- `StrictNonNullAttribute<T>`
- `SemanticNonNullAttribute`
- `SemanticNonNullAttribute<T>`

Generic Marker Types:
- `StrictNonNull<T>`
- `SemanticNonNull<T>`
- `NonNull<T>`

```csharp
[StrictNonNull<List<StringType>>]
public string Hello() => "Hello";
```

**Comment by tobias-tengler** [comment]
Very exciting! A semantic non-null will only be tagged with the `@semanticNonNull` directive in the schema for now though?

```graphql
type Product {
  name: String @semanticNonNull
}
```

It would be great to also have the proposed ability to just disable null bubbling, since code generation and IDEs won't be able to handle the directive or the new type modifier yet.

**Comment by glen-84** [comment]
> `@glen-84` `@tobias-tengler` in the spec working group we need to make sure that every graphql query that ever was created works when upgrading to a newer GraphQL spec.

I get that, but Lee's proposal _is_ backwards-compatible – if you don't apply the schema directive (`@strictNullability`), then the server behaves the same way that it did before.

Even if you added versioning to GraphQL, so that Strict Semantic Nullability could become the default, old queries would simply default to version `1.0`/`October2021`.

IMO, the best possible future outcome is what Lee suggests:

> `Type! → Type` (no null values allowed)
> `Type? → Type | SemanticNull | ErrorNull` (differentiation must be possible)
> `Type → Type | ErrorNull` (differentiation unnecessary)

For example:

```graphql
type User {
  id: ID!           # Strict non-null (neither semantic- nor error-null).
  username: String? # Nullable, but take note of any field errors (semantic-null vs error-null).
  age: Int          # Non-nullable (Int or error-null).
}
```

**Comment by tobias-tengler** [comment]
There will hopefully soon be a prototype for strict nulls (semantic non-null), so this is probably obsolete. Closing.

**Pull request closed without merging**
