### PR TITLE
Fix naming issues with generic types

### LINKED ISSUE #6392: Generated name is wrong for generic types with many type parameters
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When using a type with more than nine generic arguments, the generated GraphQL-name incorrectly contains a '_'.

See example.

### Steps to reproduce

```
    public class Query
    {
        // Generated name (OK): NineGenericsOfInt32AndInt32AndInt32AndInt32AndInt32AndInt32AndInt32AndInt32AndInt32
        public NineGenerics<int, int, int, int, int, int, int, int,int> TestNine => default!;

        // Generated name (WRONG): TenGenerics_OfInt32AndInt32AndInt32AndInt32AndInt32AndInt32AndInt32AndInt32AndInt32AndInt32
        public TenGenerics<int, int, int, int, int, int, int, int,int, int> TestTen => default!;
    }


    public class NineGenerics<T1, T2, T3, T4, T5, T6, T7, T8, T9>
    {
        public int Foo { get; set; }
    }
    public class TenGenerics<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>
    {
        public int Foo { get; set; }
    }
```

image

### Relevant log output

_No response_

### Additional Context?

I case you wonder why someone would use types with that many arguments: We use them to represent strictly typed data tables (T1 = Type of column 1, T2 = Type of column 2 etc. etc.)

Is suspect the bug to happen somewhere around here https://github.com/ChilliCream/graphql-platform/blob/f7cec169302b8f59b4a3fd28a5887eac47084da3/src/HotChocolate/Core/src/Abstractions/NameFormattingHelpers.cs#L193 (anyways, I haven't verified this)

### Version

13.4.0

### PR DESCRIPTION
**Pull request by N-Olbert**
Summary of the changes (Less than 80 chars)

- Dynamically determine the index of the `-char
- Consider `GraphQLNameAttribute` for generic types

Closes #6392 and #6293

### CODE REVIEW

**Comment by N-Olbert** [comment]
@michaelstaib We could introduce a property to configure this, how about (naming is for sure not the best)
>     [GraphQLName("Bar", IncludeTypeParameterNaming = true)]
>     public class Foo<T>
>     {
>         public T Test { get; init; }
>     }

`IncludeTypeParameterNaming = true` becomes `BarOfType`
`IncludeTypeParameterNaming = false` (default) becomes `Bar`

**Comment by michaelstaib** [comment]
I sat down with @PascalSenn to discuss it a bit ... we can still pin the legacy behavior, which is important to get this into a dot release. I modified the test a bit to include this pinning behavior. We will merge it once the build is done.

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/graphql-platform/releases/tag/13.5.0-preview.22

**Comment by michaelstaib** [comment]
Thanks again for contributing!

**Comment by ZhelninMaksim** [comment]
Is there any way I can skip or override this behavior? In the last version, I defined the names for such types myself and would like to keep that behavior, is it possible?

**Comment by N-Olbert** [comment]
@ZhelninMaksim : You may overwrite the name using a custom attribute. This has precedence.

```
public sealed class CustomGenericTypeName : DescriptorAttribute
{
    public string Name {get; init;} = default!;

    protected override void TryConfigure(IDescriptorContext context, IDescriptor descriptor, ICustomAttributeProvider element)
    {
        if (descriptor is IObjectTypeDescriptor d)
        {
            d.Name(Name);
        }
    }
}
```

**Pull request merged**
