### PR TITLE
Include net9.0 tools in StrawberryShake package

### LINKED ISSUE #7659: Include net9.0 tools in StrawberryShake package
### Product

Strawberry Shake

### Is your feature request related to a problem?

See PR https://github.com/ChilliCream/graphql-platform/pull/6395 for reference.

### The solution you'd like

Include net9.0 tools in StrawberryShake package

### PR DESCRIPTION
**Pull request by TylerSiegrist**
Summary of the changes (Less than 80 chars)

- Include net9.0 tools in StrawberryShake package

Closes #7659

### CODE REVIEW

**Comment by cmeeren** [comment]
Would be great to get this merged and released! Also being blocked by this.

**Comment by Sander0542** [comment]
I would love to see this feature released, so I can upgrade my application to .NET 9

**Comment by Cheesebaron** [comment]
Yeah even the 15.0.0-p.14 tool goes nuts like this:

```
dotnet "/Users/tomaszcielecki/.nuget/packages/strawberryshake.maui/15.0.0-p.14/build/../tools/net9/dotnet-graphql.dll" generate "/Users/tomaszcielecki/git/ApiRange/TrackMan.Api.Gql" -o "/Users/tomaszcielecki/git/ApiRange/TrackMan.Api.Gql/obj/Debug/net9.0/berry" -n TrackMan.Api.Gql -a md5
8.0.403 [/usr/local/share/dotnet/sdk]
9.0.100-rc.2.24474.11 [/usr/local/share/dotnet/sdk]
9.0.100 [/usr/local/share/dotnet/sdk]
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application '/Users/tomaszcielecki/.nuget/packages/strawberryshake.maui/15.0.0-p.14/build/../tools/net9/dotnet-graphql.dll' does not exist.
  * You intended to execute a .NET SDK command:
      A compatible .NET SDK was not found.

Requested SDK version: 6.0.100
global.json file: /Users/tomaszcielecki/.nuget/packages/strawberryshake.maui/15.0.0-p.14/build/global.json
```

Would be really nice to get this one out or at least allow roll-foward

**Comment by glen-84** [comment]
We need to add .NET 9 as a target first, and that is currently blocked by https://github.com/JasperFx/marten/pull/3558.

**Review by MoienTajik — APPROVED** [review]

**Comment by Sander0542** [comment]
> We need to add .NET 9 as a target first, and that is currently blocked by [JasperFx/marten#3558](https://github.com/JasperFx/marten/pull/3558).

This has been merged and released in https://github.com/JasperFx/marten/releases/tag/V7.33.0

**Comment by loekensgard** [comment]
Also being blocked by this, would like to see it released 😄

**Comment by Huzeyfe20** [comment]
Would like to see it released, blocked by this :)

**Comment by MoienTajik** [comment]
Hey @michaelstaib, could you please take a look at this one? It’s breaking our pipelines.

**Comment by glen-84** [comment]
https://github.com/ChilliCream/graphql-platform/pull/7741

**Review by glen-84 — APPROVED** [review]

**Comment by loekensgard** [comment]
I tried to use the new package version 14.2.0-p.2, but I keep encountering an error that states .NET 9 is missing. Could I be overlooking something?

image

**Comment by michaelstaib** [comment]
Yes .. the pr is missing the whole logic on selecting the framework

**Comment by glen-84** [comment]
@loekensgard Can you try [14.2.0-p.4](https://github.com/ChilliCream/graphql-platform/releases/tag/14.2.0-p.4)?

**Comment by loekensgard** [comment]
@glen-84, I am getting the same error as before: 

image

**Comment by glen-84** [comment]
Apologies, I was misled by #6395, thinking that that was the only change necessary. I've opened #7772.

**Comment by JaggerJo** [comment]
We are having the same issue. Updating to https://github.com/ChilliCream/graphql-platform/releases/tag/14.2.0-p.4 does not help.

**Comment by vrutten** [comment]
When can we expect this to be released?

**Comment by Malgefor** [comment]
When can we expect this to be released?

**Comment by glen-84** [comment]
Please try [14.2.0-p.7](https://www.nuget.org/packages/StrawberryShake/14.2.0-p.7).

**Comment by loekensgard** [comment]
It works 👍

**Pull request merged**
