### PR TITLE
Fix stitching "Could not resolve the actual object type from `HotChocolate.Language.NullValueNode` for the abstract type"

### LINKED ISSUE #3594: "Could not resolve the actual object type" error when `null` returned in list of interfaces
Schema
```
type Query{
  test: [BaseType]
}
interface BaseType {
  name: ID!
}
type ConcreteType implements BaseType {
  name: ID!
}
```
Query
```
query {
  test {
    __typename
  }
}
```
Response
```
{
  "errors": [
    {
      "message": "Could not resolve the actual object type from `HotChocolate.Language.NullValueNode` for the abstract type `test`.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "test",
        0
      ]
    }
  ],
  "data": {
    "test": [
      null
    ]
  }
}
```

**Expected behavior**
`null` should be returned in list without errors.

**Additional context**
HC v11.2.2

### PR DESCRIPTION
**Pull request by gao-artur**
Closes #3594

### CODE REVIEW

**Comment by michaelstaib** [comment]
Can you add a test for this? I will add it to 12.9 once we have a tests.

**Comment by gao-artur** [comment]
Trying to understand where and how to add the test. Is it correct to assume I need to add the schema under `SpecialCases` folder and the test in `FederatedSchemaTests` class?
image

**Comment by michaelstaib** [comment]
can you describe the test a bit ... then I can help you better with it? What situation do we need to create to make the old implementation break.

**Comment by gao-artur** [comment]
I need the remote server to implement the following schema (array of nullable interfaces)
```
type Query{
  test: [BaseType]
}
interface BaseType {
  name: ID!
}
type ConcreteType implements BaseType {
  name: ID!
}
```

And send the query via the stitching gateway
```
query {
  test {
    __typename
  }
}
```

**Comment by michaelstaib** [comment]
OK ... I will add the test ... I think I can do it quite quickly.

**Comment by gao-artur** [comment]
@michaelstaib did you manage it?

**Comment by gao-artur** [comment]
@michaelstaib any update?

**Comment by michaelstaib** [comment]
hey @gao-artur can you sign the CLA so we can merge this?

**Comment by gao-artur** [comment]
@michaelstaib done.

**Pull request closed without merging**
