### PR TITLE
Fixed memory leak caused by query variables (#5383)

### PR DESCRIPTION
**Pull request by lweberprb**
This backports #5383 to version 12.

### CODE REVIEW

**Comment by lweberprb** [comment]
@michaelstaib

**Comment by michaelstaib** [comment]
Thank you for your help! Appreciate it. I will do a review tonight and then we will do a new build for 12.

**Comment by declan-bourke** [comment]
@michaelstaib did this go into a version 12 release?

**Comment by declan-bourke** [comment]
@michaelstaib - actually ignore my previous comment - I have been doing further testing with the new fix and the issue still exists due to it not handling List<KeyValuePair<string, object?>> which is what the Formatter generates.

I will see if I can create a commit on this branch and a separate one for version 13.

**Comment by declan-bourke** [comment]
I'm not sure if it has worked but I have created a PR here:

https://github.com/lweberprb/hotchocolate/pull/1

I will also create one for version 13

**Comment by michaelstaib** [comment]
We are not fixing this anymore in version 12 ... with version 13.1 there is now no more reason to not upgrade.

**Pull request closed without merging**
