### PR TITLE
Optimize filter expressions

### LINKED ISSUE #6996: Optimize FilterExpressionBuilder by using cached delegates and MethodInfo
### Product

Hot Chocolate

### Is your feature request related to a problem?

Hey guys!

I submitted a PR to fix the expression constant issue which was merged a while back: https://github.com/ChilliCream/graphql-platform/pull/6711

While looking through the code for that PR i was wondering if it would be possible to optimize the expression logic for the filter expression builder even further.

There's a couple of low hanging fruits as far as i can tell

### The solution you'd like

, related to:

### Contains expression

The Expression.Call overload used in the FilterExpressionBuilder.In method causes about 5 KB of allocations from the method call alone, since the underlying expression code retrieves all methods from the Enumerable type on each invocation. Using a cached MethodInfo here results in approximately 95% improvement in both speed and allocations, see benchmarks below.

### Cached delegates instead of reflection

Currently, all the filter expressions uses reflection to invoke the generic CreateAndConvertParameter<T> method. Instead of using reflection every time a filter expression is built, it's possible to cache the delegate after the call to MakeGenericMethod and then use the delegate directly instead through reflection.

This eliminates a reflection call, multiple cases of boxing and reflection argument allocations while also being around twice as fast.

I've tested the changes in one of our API's and the results seem to be quite substantial, especially for the IN / NIN filters. I've tested against a moderate set of different queries with combinations of different operators and everything seems to be running great.

### Benchmarks

hc-delegate-optimization

The code itself is not altered in any significant way, and this was achieved by only changing the internal code of the FilterExpressionBuilder and introducing a couple of ConcurrentDictionary instances to store the cached delegates and method-info's for the different types.

I'll throw together a PR some time this week, any initial thoughts on this @PascalSenn or @michaelstaib ? This seems like a great improvement considering HC's performance goals, but for all i know there might be reasons that this hasn't been done already, let me know if you see anything obviously wrong with this approach, otherwise i'll get some actual code for you to look at soon :)

### PR DESCRIPTION
**Pull request by nikolai-mb**
Adds delegate caching for filter expressions using concurrent dictionaries for improved performance and reduced allocations.

Second commit is only related to in / nin filters and eliminates a 5.5 KB allocation that occurs every time the expression is applied by caching MethodInfo for invoking Expression.Call

Closes #6996

### CODE REVIEW

**Comment by nikolai-mb** [comment]
Benchmarks:

Commit https://github.com/ChilliCream/graphql-platform/pull/7005/commits/be56f19947c443e06e1be2abcade6cecdcb307a9 - applies to all filters except for All / Any / some / None

| Method         | Mean       | Error    | StdDev   | Ratio | Gen0   | Allocated | Alloc Ratio |
|--------------- |-----------:|---------:|---------:|------:|-------:|----------:|------------:|
| ContainsOld    |   645.6 ns |  6.78 ns |  5.66 ns |  1.00 | 0.0134 |     744 B |        1.00 |
| ContainsNew    |   353.7 ns |  1.06 ns |  0.83 ns |  0.55 | 0.0100 |     512 B |        0.69 |
|                |            |          |          |       |        |           |             |
| EqualsOld      |   377.4 ns |  1.39 ns |  1.09 ns |  1.00 | 0.0095 |     488 B |        1.00 |
| EqualsNew      |   152.3 ns |  0.57 ns |  0.51 ns |  0.40 | 0.0050 |     256 B |        0.52 |
|                |            |          |          |       |        |           |             |
| GreaterThanOld |   374.2 ns |  0.87 ns |  0.73 ns |  1.00 | 0.0095 |     488 B |        1.00 |
| GreaterThanNew |   156.4 ns |  0.86 ns |  0.72 ns |  0.42 | 0.0050 |     256 B |        0.52 |
|                |            |          |          |       |        |           |             |
| InOld          | 3,776.9 ns | 20.80 ns | 16.24 ns |  1.00 | 0.1068 |    5840 B |        1.00 |
| InNew          | 3,603.7 ns | 28.56 ns | 25.31 ns |  0.95 | 0.1068 |    5608 B |        0.96 |
|                |            |          |          |       |        |           |             |
| LowerThanOld   |   374.4 ns |  2.12 ns |  1.88 ns |  1.00 | 0.0095 |     488 B |        1.00 |
| LowerThanNew   |   150.9 ns |  0.20 ns |  0.18 ns |  0.40 | 0.0050 |     256 B |        0.52 |
|                |            |          |          |       |        |           |             |
| NotContainsOld |   647.7 ns |  1.20 ns |  0.94 ns |  1.00 | 0.0153 |     792 B |        1.00 |
| NotContainsNew |   358.1 ns |  0.86 ns |  0.72 ns |  0.55 | 0.0110 |     560 B |        0.71 |
|                |            |          |          |       |        |           |             |
| NotEqualsOld   |   377.8 ns |  1.08 ns |  0.90 ns |  1.00 | 0.0095 |     488 B |        1.00 |
| NotEqualsNew   |   154.0 ns |  0.34 ns |  0.28 ns |  0.41 | 0.0050 |     256 B |        0.52 |
|                |            |          |          |       |        |           |             |
| StartsWithOld  |   629.4 ns |  2.56 ns |  2.00 ns |  1.00 | 0.0134 |     744 B |        1.00 |
| StartsWithNew  |   369.2 ns |  3.82 ns |  3.57 ns |  0.59 | 0.0100 |     512 B |        0.69 |

Commit https://github.com/ChilliCream/graphql-platform/pull/7005/commits/51ae3fe65d23065d3aa40975c4e9f5e0d84ff9a4  - only applies to in / nin

| Method | Mean       | Error    | StdDev   | Ratio | Gen0   | Allocated | Alloc Ratio |
|------- |-----------:|---------:|---------:|------:|-------:|----------:|------------:|
| InOld  | 3,643.0 ns | 40.09 ns | 37.50 ns |  1.00 | 0.1068 |    5608 B |        1.00 |
| InNew  |   231.1 ns |  2.65 ns |  2.48 ns |  0.06 | 0.0057 |     288 B |        0.05 |

Commit https://github.com/ChilliCream/graphql-platform/pull/7005/commits/56316947333d94b7c97acc1e51143aea1bdbf7f5 - only applies to All / Any / Some / None

Did not include None / Some since they are just All / Any wrapped with a `Not` expression.

| Method | Mean     | Error   | StdDev  | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|------- |---------:|--------:|--------:|------:|--------:|-------:|----------:|------------:|
| AllOld | 256.3 ns | 2.33 ns | 2.18 ns |  1.00 |    0.00 | 0.0062 |     312 B |        1.00 |
| AllNew | 245.8 ns | 0.97 ns | 0.81 ns |  0.96 |    0.01 | 0.0052 |     272 B |        0.87 |
|        |          |         |         |       |         |        |           |             |
| AnyOld | 261.8 ns | 3.56 ns | 3.33 ns |  1.00 |    0.00 | 0.0062 |     312 B |        1.00 |
| AnyNew | 250.5 ns | 3.31 ns | 2.93 ns |  0.96 |    0.02 | 0.0052 |     272 B |        0.87 |

**Comment by nikolai-mb** [comment]
Added two additional commits that cache the default expression for representing a null value for a given type as well as constant expressions for representing boolean true and false. This avoids a lambda expression allocation for these values when used in a filter

**Review by PascalSenn — APPROVED** [review]
Thanks @nikolai-mb for the pull request, very clean PR.

Just changed a few formatting things
@michaelstaib  LGTM, if tests are green, lets go

**Comment by michaelstaib** [comment]
will go in today

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
Hey @nikolai-mb,

I send this trough our tests and it breaks 78 tests ... 

Have you run the data tests?

image

**Review by michaelstaib — CHANGES_REQUESTED** [review]
Tests Fail

**Comment by michaelstaib** [comment]
It looks like the parameters get removed

```
  false SQL:
  ---------------
- .param set @__p_0 0
- 
  SELECT "d"."Id", "d"."Bar"
  FROM "Data" AS "d"
- WHERE "d"."Bar" = @__p_0
+ WHERE NOT ("d"."Bar")
  ---------------
```

**Comment by nikolai-mb** [comment]
> Have you run the data tests?

No, i assumed the same tests would run as part of the PR pipeline. I've tested the code against a real API running sql server and EF Core and so i was confident in the code submitted. I'll have a look at the data-tests specifically when i have a minute, sorry for the inconvenience

**Comment by nikolai-mb** [comment]
Pushed two fixes, the first one fixes the lack of parameterization from https://github.com/ChilliCream/graphql-platform/pull/7005#issuecomment-2039085700

Second one fixes a Nullable&lt;bool&gt; == bool comparison which resulted in expressions that were invalid. Resolved this by introducing two additional expressions for nullable true and false.

I have some noise in my tests and several snapshot tests are failing due to only CRLF / LF diff not sure if that's the case for you.

Apologies for overlooking this, could you do another sanity check and run the tests on your end with the latest changes?

**Comment by michaelstaib** [comment]
its the same tests. But somehow the build agent looks green.

**Comment by michaelstaib** [comment]
@nikolai-mb thank you for your contribution!

**Pull request merged**
