### PR TITLE
Partial fix of #6257 (StrawberryShake generator gets confused over ra…

### PR DESCRIPTION
**Pull request by ademchenko**
Partial fix of #6257 

The remaining problem is that the generated code contains only the registration of JsonSerialiazer with the default name "Any" (see the method ConfigureClient):
```global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::StrawberryShake.Serialization.ISerializer, global::StrawberryShake.Serialization.JsonSerializer>(services);```

That causes the error in the result builder ctor:
```_jSONParser = serializerResolver.GetLeafValueParser<global::System.Text.Json.JsonElement, global::System.Text.Json.JsonDocument>("JSON") ?? throw new global::System.ArgumentException("No serializer for type `JSON` found.");```
because the serializer with the key "JSON" is not found.

Adding the serializer into the service collection manually solves the issue:
`global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::StrawberryShake.Serialization.ISerializer, 
                global::StrawberryShake.Serialization.JsonSerializer>(serviceCollection, _ => new global::StrawberryShake.Serialization.JsonSerializer("JSON"));`

But that would be awesome if that line is added not manually but at the stage of the code generation.  @michaelstaib. could you help with that, please?

### CODE REVIEW

**Comment by michaelstaib** [comment]
I am looking into this now.

**Comment by ademchenko** [comment]
@michaelstaib , is there any movement with the review of that issue and merging it into the service brunch?

**Comment by mattszmigiel** [comment]
I am also affected by the bug. Any updates for now?

**Comment by clazarev** [comment]
How about using the new UTs from #6313 in case another built-in scalar is introduced?

**Comment by davidst** [comment]
I am also affected by the bug. Any updates on this?

**Comment by michaelstaib** [comment]
We have still one issue on this fix.

**Comment by niles11** [comment]
Is it possible to give an estimate to when this bugfix will be part of a new StrawberryShake release?

**Comment by ryanrivest** [comment]
Anything we can do to help this one get released?  We would love to be on v13.

**Comment by niles11** [comment]
Is there any way I can help to get this fix into a release? In our team, we have been able to work around this issue so far but we are now at the point where we no longer can and it's becoming an impediment. I saw @michaelstaib's answer in which he says there is still one issue. I would like to know what the actual issue is so I can assist to fix this issue. Hopefully then, we can get this into a release as soon as possible.

**Comment by glen-84** [comment]
@ademchenko @michaelstaib

According to the author of #6257 (above), this is no longer an issue since 13.8.0, and may have been fixed in #6683.

I was also unable to reproduce #5899.

I think that this PR can be closed.

**Pull request closed without merging**
