### PR TITLE
Updated extending-filtering.md

### PR DESCRIPTION
**Pull request by den4ik124**
Constructor `QueryableStringInvariantContainsHandler` was changed to `QueryableStringInvariantEqualsHandler`

I hope it was just a typo because of copy-pasting 😅
P.s. sorry in advance if some required steps for page editing were missing

### CODE REVIEW

**Comment by glen-84** [comment]
@den4ik124 Could you please update this in the v14 docs as well? Thanks for your contribution.

**Comment by den4ik124** [comment]
> @den4ik124 Could you please update this in the v14 docs as well? Thanks for your contribution.

@glen-84 changes were made for v14 also.

**Review by glen-84 — APPROVED** [review]

**Comment by den4ik124** [comment]
Sorry @glen-84 , maybe you know what does "action required" means?
https://github.com/ChilliCream/graphql-platform/actions/runs/10246663984

Do I need to do something or someone else need to leave approve on it?

**Comment by glen-84** [comment]
@den4ik124 We needed to approve the workflow run, which I've done now. Nothing else is required from your side. Thanks.

**Comment by glen-84** [comment]
@den4ik124 It's not necessary to merge `main` unless there are conflicts. Thanks.

**Comment by michaelstaib** [comment]
Thank you for contributing

**Pull request merged**
