### PR TITLE
Feat ignore additional input fields (#6307)

### LINKED ISSUE #6307: Allow overposting extra fields on input objects.
### Product

Hot Chocolate

### Is your feature request related to a problem?

There are cases where it's convenient to just over-post data to a mutation and let the server discard the additional properties. For example I may load a list of objects with additional properties, change a couple, and send the whole record back rather than re-map it down to just the basic input object type.

However, the [`InputFormatter`](https://github.com/ChilliCream/graphql-platform/blob/13.2.1/src/HotChocolate/Core/src/Types/Types/InputFormatter.cs#L273) and [`InputParser`](https://github.com/ChilliCream/graphql-platform/blob/13.2.1/src/HotChocolate/Core/src/Types/Types/InputParser.cs#L274) both return errors when encountering unknown fields.

### The solution you'd like

It would be nice to be able to specify either as a config default or per-type if extra fields should be ignored.

### PR DESCRIPTION
**Pull request by leniency**
Add configuration options to the `InputParser` to allow it to ignore and discard additional input data. This allows easier client-side read/update patterns with minimal mapping between types. The `InputParser` can be registered with the DI services. This is an opt-in feature and does not break existing functionality.

Closes #6307

### CODE REVIEW

**Comment by michaelstaib** [comment]
I have looked at it and looks good for the most part ... I think there is a bit polish needed for the configuration part .... 

maybe something like:

```graphql
services.AddGraphQLServer()
    .AddInputParser(o => o.Ignore....)
```

This would make for a nicer configuration.... 

What do you think?

**Comment by michaelstaib** [comment]
I targeted 13.6 ... if we cannot get it in by then we can move it to 13.7, so no pressure.

**Comment by leniency** [comment]
> ```graphql
> services.AddGraphQLServer()
>     .AddInputParser(o => o.Ignore....)
> ```

That does look nicer and more discoverable. I'll get the extension method added an update the pull request.
Thanks!

**Comment by leniency** [comment]
Updated the configuration options to be fluent and chainable:

```csharp
services
    .AddGraphQLServer()
    .AddInputParser(options =>
    {
        options.IgnoreAdditionalInputFields = true;
    })
    ....;
```

If `AddInputParser` is omitted, then the default options will be used (original handling of throwing errors).

**Review by michaelstaib — APPROVED** [review]

**Pull request merged**
