### PR TITLE
Attempt fixing nested variable forwarding in Fusion

### PR DESCRIPTION
**Pull request by martindisch**
With a query containing nested fields with arguments such as
```graphql
query ProductReviews(
  $id: ID!
  $first: Int
) {
  node(id: $id) {
    ... on Product {
      id
      reviews(first: $first) {
        body
      }
    }
  }
}
```
the variables going to the nested fields (in this case `$first`) don't get forwarded to the subgraph, because while resolving the requirements the request formatter only considers the variables of the top-level field of the current selection (`node`), not those of its children.
The gateway returns the error "The following variables were not declared: first." originating from the subgraph missing its variable.

This can be "fixed" by the change in this PR, although it's definitely not a sensible solution. Do you have any ideas as to the proper way of dealing with that?

### CODE REVIEW

**Comment by michaelstaib** [comment]
This fix is not the solution ... I am working on a proper fix at the moment ...

**Comment by martindisch** [comment]
Excellent, that's what we've been hoping for! Feel free to close this once you have something.

**Comment by michaelstaib** [comment]
I have found a couple more cases that were not working ... like nested variables and so on. We will ship the fix with 13.2.1 today.

**Review by michaelstaib — APPROVED** [review]

**Comment by martindisch** [comment]
Great stuff, thanks for the proper fix!

**Pull request merged**
