### PR TITLE
Fixed StrawberryShake result has empty Extensions Issue

### LINKED ISSUE #4956: StrawberryShake result has empty Extensions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The property `Extensions` of `ExecuteAsync` result seems to be always empty even if a GraphQL server returns extension data.

### Steps to reproduce

1. Use the attached solution
2. Build and run

### Actual results

StrawberryShake has no extension data:

```
StrawberryShake Extensions.Count = 0
HttpClient extensions = {
  "requestId": "de6db3fd-3013-45c6-a38d-c58e72d99110"
}
```

### Expected results

StrawberryShake has some extension data:

```
StrawberryShake Extensions.Count = 1
HttpClient extensions = {
  "requestId": "de6db3fd-3013-45c6-a38d-c58e72d99110"
}
```

### Additional Context?

[StrawberryShakeEmptyExtensions.zip](https://github.com/ChilliCream/hotchocolate/files/8451147/StrawberryShakeEmptyExtensions.zip)

### Product

Strawberry Shake

### Version

12.7.0

### PR DESCRIPTION
**Pull request by anton-gogolev**
This is my naïve attempt to fix #4956.

There are no meaningful tests for this fix; I hacked around existing one to get this thing to kinda-sorta work to fit my use-case. I'm all ears and open to suggestions as to how improve this PR.

### CODE REVIEW

**Comment by michaelstaib** [comment]
Hey there,

thank you for contributing.

Can you add some integration tests so that we can see that this works?

**Comment by anton-gogolev** [comment]
@michaelstaib Not sure about _integration_ tests, but I added a simple unit test that does some basic assertions.

From what I could understand, objects of `Response` class have very few properties ever initialized, so spinning up a full GraphQL server and then invoking it from an integration test sounds a bit excessive: we can just "pretend" that whatever we've got a JSON document from the wire and just "build" an `OperationResult` instance out of it.

**Comment by anton-gogolev** [comment]
@michaelstaib What would be my (or some else's) next steps on this?

**Comment by nightroman** [comment]
@michaelstaib What else is needed? Can this fix make into 13.1? How can we help in addition to the @anton-gogolev fix and unit test? The `extensions` filed is part of GraphQL specs and Strawberry Shake not respecting it causes real pain...

**Comment by michaelstaib** [comment]
Yes

**Comment by michaelstaib** [comment]
We will add it to 13.1

**Comment by michaelstaib** [comment]
Should be merged after the weekend and available as preview

**Comment by nightroman** [comment]
@michaelstaib Thank you, it a great news!!! @anton-gogolev many thanks for the fix!

**Comment by anton-gogolev** [comment]
@michaelstaib A friendly ping here. Is anything required here from me?

**Comment by nightroman** [comment]
@michaelstaib https://github.com/ChilliCream/graphql-platform/releases/tag/13.1.0-preview.5 is out with this fix promised to be included 

> Should be merged after the weekend and available as preview

It's all right if it is not forgotten as such and will get into 13.1. But we worry a little... and we do not have a chance to test a preview, who knows, the merge may bring surprises.

**Comment by nightroman** [comment]
@michaelstaib could you please merge this PR so that it is included in the preview and we can test? We promise to test and report whatever the outcome is. You should be interested in any outcome and our feedback, right?

**Comment by RobAltium** [comment]
@michaelstaib Sorry to nag ... can this be merged please?  Who else can review?  This is holding up @anton-gogolev and our Altium365 team...

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
Its merged and will be in the next build.

**Pull request merged**
