### PR TITLE
WIP: Neo4J language updates for pieces required for mutations 

### PR DESCRIPTION
**Pull request by arif-hanif**
- Add Create, Set, Merge, Remove, Delete clauses

### CODE REVIEW

**Comment by michaelstaib** [comment]
Does this need a review or is it still a draft?

**Comment by arif-hanif** [comment]
Still a draft, i have to write a bunch of language tests

**Comment by glen-84** [comment]
@michaelstaib Now that Neo4J support has been [removed](https://github.com/ChilliCream/graphql-platform/pull/6655), shall we close this?

**Comment by glen-84** [comment]
Closing, as Neo4j support has been [removed](https://github.com/ChilliCream/graphql-platform/pull/6655) in v14.

**Pull request closed without merging**
