### PR TITLE
WIP: Translate `Microsoft.AspNetCore.Authorization.AuthorizeAttribute` to `@authorize` directive

### LINKED ISSUE #3847: Align `HotChocolate.AspNetCore.AuthorizeAttribute` to `Microsoft.AspNetCore.AuthorizeAttribute`
**Is your feature request related to a problem? Please describe.**
The way of defining Roles using the `Authorize` attribute differs between Hot Chocolate and the official attribute.

Hot Chocolate:
```csharp
[Authorize(Roles = new[] { "Role" })]
[Authorize(Roles = new[] { "Role1", "Role2" })]
```

ASP.NET Core:
```csharp
[Authorize(Roles = "Role")]
[Authorize(Roles = "Role1,Role2"]
```

Hot Chocolate's version is more annoying to type, especially if you only have one role. It also makes it harder to just copy over existing `Authorize` definitions from a REST API project for example.

**Describe the solution you'd like**
Hot Chocolate's `Authorize` attribute should also accept a comma separated string for its `Roles` property. This change can't be performed without introducing a breaking change immediately or making a compromise by renaming the property. Therefor we could also introduce a new attribute `GraphQLAuthorize` where the type of the property is correct. This would also solve the ambiguity between the two `Authorize` attributes, which could be the cause of some confusion currently.

### PR DESCRIPTION
**Pull request by tobias-tengler**
Adds a new TypeInterceptor that is automatically registered when calling `AddAuthorize` to translate the `Microsoft.AspNetCore.Authorization.AuthorizeAttribute` to the `@authorize` directive.

This could be a breaking change for existing schemas, if Microsoft's `AuthorizeAttribute` was used by accident instead of Hot Chocolate's `AuthorizeAttribute`. But it will also prevent these accidental mixups in the future, by just providing the same functionality consistently. I thought about making the Hot Chocolate `AuthorizeAttribute` obsolete, but there are still valid use cases like `AFTER_RESOLVER` and also the limitation of not being able to specify the Microsoft attribute on properties.

Closes #3847 

#### Todos
- Infer attribute from type extensions

#### Outlook
I would like to add `AuthenticationSchemes` to the `@authorize` directive (and all APIs around it) to allow the use of multiple authentication schemes.

### CODE REVIEW

**Comment by PascalSenn** [comment]
@tobias-tengler  how far was this PR ? :)

**Comment by tobias-tengler** [comment]
> @tobias-tengler  how far was this PR ? :) 

I think it was almost done, except for some todos in the code and the missing ability to convert the Microsoft attribute, when it was applied on a type extension. I think it was tricky, because the type interceptor could not see the original CLR types where the extended field was coming from, so the attribute on the type can not be read. I think there should be a failing test.

**Comment by tobias-tengler** [comment]
Probably should be revisited as part of a 13 dot releases that focuses on security aspects, but closing for now.

**Comment by michaelstaib** [comment]
Abandoning this as it poses issues with the new approach towards auth

**Pull request closed without merging**
