### PR TITLE
Support legacy strongly typed Ids

### PR DESCRIPTION
**Pull request by tobias-tengler**
This adds support to parse Ids in legacy format using a custom `INodeIdValueSerializer`.

If you had previously defined Type Converters for custom / composite Id types, like
```csharp
builder
    .AddTypeConverter<DeviceId, int>(x => x.Value)
    .AddTypeConverter<int, DeviceId>(x => new DeviceId(x))
    .BindRuntimeType<DeviceId, IdType>()
```

you can now simply implement and register a `INodeIdValueSerializer` for your Id, which takes care of parsing your custom Ids both in the legacy and new format. Only new Ids are being output.

### CODE REVIEW

**Comment by tobias-tengler** [comment]
We also have some custom Ids that use `:` as a delimiter within the value portion of the Id. This is problematic, as this would be seen as the delimiter for typename and Id value of the new Id format and would lead to parsing errors.

**Comment by michaelstaib** [comment]
> We also have some custom Ids that use : as a delimiter within the value portion of the Id. This is problematic, as this would be seen as the delimiter for typename and Id value of the new Id format and would lead to parsing errors.

This should not be a problem as we are only looking for the first colon

**Comment by tobias-tengler** [comment]
It's a problem if the Id comes in the legacy format.

**Comment by michaelstaib** [comment]
> It's a problem if the Id comes in the legacy format.

yes .... as it would mean we first have to make sure its not the legacy format.

**Comment by tobias-tengler** [comment]
It's a bit tricky as compressed Guids can contain a new line character. If we move the check for the new line character, i.e. legacy detection, before the check for `:`, we might interpret a new compressed Guid Id as a legacy Id. Even if we check the type annotation after the new line (`d`, `i`, `l` &`g`) there might still be a collision. I think this case with `:` is pretty specific, so I think I'd rather try to start phasing out this Id format on our side now in preparation for v14. I don't want to bloat the hot path with legacy detection for a 0.001% case.

**Comment by michaelstaib** [comment]
Yes ... also I would not like to have overhead for the legacy format.

**Pull request merged**
