### PR TITLE
Fix query subscriptions not emitting data

### LINKED ISSUE #5704: Generated component displays data only once with default execution strategy
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

If data returned by a GraphQL query doesn't change between calls, then its generated `<Use... />` component with default execution strategy (NetworkOnly) displays the data only the first time it's accessed. If you navigate away from a page with the component and come back, the call to the GraphQL API end-point is made, but the data is not displayed.

### Steps to reproduce

1. Write a query that will always return the same data (for example crypto names only)
2. Run `dotnet build` to generate code
3. Put the generated `<Use... />` component on a page and provide content for `ChildContent` (do not change the default execution strategy)
4. Run the app and navigate to that page (API call returns data which is displayed correctly)
5. Navigate away and come back to the page (API call returns the same data as before, but it is not displayed)

### Relevant log output

_No response_

### Additional Context?

Here's a simple app I've created to reproduce the issue:
https://github.com/elishnevsky/StrawberryShakeBug

### Version

13.0.0-rc.0

### PR DESCRIPTION
**Pull request by Sibusten**
Fix query subscriptions not emitting data in various cases.

There are some issues with `OperationExecutor` that cause query subscriptions to not return any data.

1. After performing the network request, the `observer` is always completed. This is correct for subscriptions, but should not be done for queries, as it will prevent them from receiving updates from the entity store.
2. Subsequent executions of a query with the `NetworkOnly` strategy will not emit any results if the data does not change between requests. This is due to the entity store internally skipping the update notification for duplicate results.

This PR modifies the executor's logic to instead send results directly to the `observer`, while still avoiding duplicate messages in the case of `CacheAndNetwork` and `Subscription` requests. The entity store subscription is always subscribed to in all query strategies, and the observable is never completed for queries.

The completion logic was moved from the `finally` into the end of the `try`, since [the observable contract](https://reactivex.io/documentation/contract.html) states that only one of `OnError` and `OnCompleted` should be called, not both. Previously an exception would have caused both to be called.

Closes #5704

### CODE REVIEW

**Comment by michaelstaib** [comment]
Thank you for contributing ... give us a ping once you want a review.

**Comment by Sibusten** [comment]
@michaelstaib I couldn't find tests for this file, so I added a bunch of cases that should cover everything related to queries. Ready for review now

**Comment by michaelstaib** [comment]
@Sibusten I will have a look at it. Thank you for contributing!

**Review by valincius — APPROVED** [review]

**Review by michaelstaib — APPROVED** [review]

**Pull request merged**
